### ISSUE TITLE
Error: InvalidBucketName: The specified bucket name is not valid.

### ISSUE THREAD

**Issue by yaoyaojia** [shallwefootball/s3-static-action#69]
```
  - name: Upload to S3
        uses: shallwefootball/upload-s3-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.CF_R2_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CF_R2_SECRET_ACCESS }}
          aws_bucket: node_sh
          source_dir: cdn
          endpoint: ${{ secrets.CF_R2_ENDPOINT }}
```
