### ISSUE TITLE
Error: Unable to resolve action. Repository not found: shallwefootball/s3-upload-action

### ISSUE THREAD

**Issue by shivakuriyadiupkeep** [shallwefootball/s3-static-action#70]
I am getting an error "Error: Unable to resolve action. Repository not found: shallwefootball/s3-upload-action". Please look into this.
Thank you

**Comment by brentasauras** [comment]
I'm also getting the same error.

**Comment by ajtrichards** [comment]
This is a typo in the documentation. You should have this;

```
name: Deploy
      uses: shallwefootball/upload-s3-action@master
      with:
        source_dir: ./
        aws_bucket: "YOURBUCKET"
        aws_key_id: ${{ secrets.AWS_SECRET_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
```

Notice that the `uses` says `uses: shallwefootball/upload-s3-action@master` and NOT `shallwefootball/s3-upload-action`
